version: 2.1
defaults: &imag   # defaults to be reuse
    docker:
      #- image: cimg/base:2020.01
      - image: circleci/node:13.8.0

commands:
  myfunction:
    parameters:
      to: 
        type: string
        default: "id of circle project"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID > ~/output.txt   # \<< $CIRCLE_BRANCH \>> branch
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
jobs:
  save_hello_world_output:
    <<: *imag
    steps:
      - myfunction:
          to: " argoooo "
      
      #- run: return 1
  print_output_file:
    <<: *imag
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
      
     # - when: on_fail
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      # - welcome/run
      - save_hello_world_output
      - print_output_file:
          requires:
             - save_hello_world_output